// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3-r-Q_VkYedV6Wc6epEPmAaXX3lUJXgA',
    appId: '1:502926492471:web:400f98c64e2415052250b2',
    messagingSenderId: '502926492471',
    projectId: 'fir-auth-1b027',
    authDomain: 'fir-auth-1b027.firebaseapp.com',
    storageBucket: 'fir-auth-1b027.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7zUTynhPJ1el1rGMo-ljGmVrTIAGhnCI',
    appId: '1:502926492471:android:7c23bad1cb91c1cd2250b2',
    messagingSenderId: '502926492471',
    projectId: 'fir-auth-1b027',
    storageBucket: 'fir-auth-1b027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBW62R-86eEJ27XYjTDmGorJS-uOutNLE',
    appId: '1:502926492471:ios:d0d4cd43458159152250b2',
    messagingSenderId: '502926492471',
    projectId: 'fir-auth-1b027',
    storageBucket: 'fir-auth-1b027.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBW62R-86eEJ27XYjTDmGorJS-uOutNLE',
    appId: '1:502926492471:ios:f7cefdab428cccc22250b2',
    messagingSenderId: '502926492471',
    projectId: 'fir-auth-1b027',
    storageBucket: 'fir-auth-1b027.appspot.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
